### ISSUE TITLE
--collaborator-color-* variables present in dist CSS files

### ISSUE THREAD

**Issue by hubgit** [substance/substance#1053]
In the dist folder of npm releases, the CSS files still contain a few variables, around line 824:

```css
.sc-text-property .se-selection-fragment.sm-collaborator-1  { background: rgba(--collaborator-color-1, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-2  { background: rgba(--collaborator-color-2, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-3  { background: rgba(--collaborator-color-3, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-4  { background: rgba(--collaborator-color-4, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-5  { background: rgba(--collaborator-color-5, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-6  { background: rgba(--collaborator-color-6, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-7  { background: rgba(--collaborator-color-7, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-8  { background: rgba(--collaborator-color-8, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-9  { background: rgba(--collaborator-color-9, 0.30); }
.sc-text-property .se-selection-fragment.sm-collaborator-10 { background: rgba(--collaborator-color-10, 0.30); }
```

The `--collaborator-color-{n}` variables need to be replaced with the actual values during the build process.
