### ISSUE TITLE
Modular ToolBar implementation plan

### ISSUE THREAD

**Issue by michael** [substance/substance#171]
Desired usage to define a customized toolbar:

``` js
var writerTools = [
  $$(ToolGroup).append(
    $$(SwitchTextTypeTool) // uses surface configuration to populate text types dropdown
  ),
  $$(ToolGroup).append(
    $$(Strong),
    $$(Emphasis)
  ),
  $$(ToolDropdown, {label: 'Figures'}).append(
    $$(InsertFigureTool)
  )
];

// Always use the official Substance Toolbar component, so we can ensure a defined markup for all toolbars
$$(Toolbar).append(writerTool);
```

The regular anno tools are 'weak components' (or element components) meaning that they can't exist on their own and that they are styled by their wrapping component. e.g. ToolGroup. This makes it possible to use the same component in different contexts. e.g. the strong tool wrapped in a tool dropdown

``` html
<div class="sc-tool-bar">
  <div class="se-tool-group">
    <div class="se-tool"><i class="fa fa-icon-bold"></i><span class="se-label">Strong</span></div>
    <div class="se-tool"><i class="fa fa-icon-emphasis"></i><span class="se-label">Strong</span></div>
  </div>
  <div class="se-tool-dropdown sm-open">
    <div class="se-toggle">Figures</div>
    <div class="se-options">
      <div class="se-tool"><i class="fa fa-icon-figure"></i><span class="se-label">Insert Figure</span></div>
    </div>
  </div>
</div>
```

All toolbar-related styles will live in `_toolbar.scss`.

``` css
.sc-toolbar {
  height: 40px;
  overflow: auto;
  ...
}

.se-tool-group {
  float: left;
  border-right: 1px solid #ddd; // little separator betweeen groups
}

.se-tool-dropdown .se-tool-options {
  ...
}
```
