### ISSUE TITLE
Get rid of high z-indexes as used in scrollbar and toolbar styles

### ISSUE THREAD

**Issue by michael** [substance/substance#191]
``` css
.scrollbar-component .thumb {
  ...
  z-index: 4000;
  ...
}
```
